FROM alpine:latest

ARG FRPC_VERSION=0.69.1

LABEL maintainer="Ac.All.Sh <https://github.com/Ac-All-Sh>"
LABEL description="frpc - Fast Reverse Proxy Client"
LABEL version="${FRPC_VERSION}"

RUN apk add --no-cache \
    ca-certificates \
    && adduser -D -H -s /bin/false frpc

WORKDIR /etc/frp

COPY frpc /usr/local/bin/frpc
RUN chmod +x /usr/local/bin/frpc

RUN mkdir -p /var/log/frp && chown frpc:frpc /var/log/frp

USER frpc

ENTRYPOINT ["frpc"]
CMD ["-c", "/etc/frp/frpc.toml"]
